package com.highradius.model;

public class Invoice {
	private String DISTRIBUTION_CHANNEL, DIVISION, PURCHASE_ORDER_TYPE, ORDER_CREATION_DATE, ORDER_CREATION_TIME,
			CREDIT_CONTROL_AREA, REQUESTED_DELIVERY_DATE, ORDER_CURRENCY, CREDIT_STATUS;
	private int ID, CUSTOMER_ORDER_ID, SALES_ORG, COMPANY_CODE, SOLD_TO_PARTY, CUSTOMER_NUMBER;
	private double RELEASED_CREDIT_VALUE, ORDER_AMOUNT, AMOUNT_IN_USD;
	private long UNIQUE_CUST_ID;

	public Invoice() {
	}

	public Invoice(String dISTRIBUTION_CHANNEL, String dIVISION, String pURCHASE_ORDER_TYPE, String oRDER_CREATION_DATE,
			String oRDER_CREATION_TIME, String cREDIT_CONTROL_AREA, String rEQUESTED_DELIVERY_DATE,
			String oRDER_CURRENCY, String cREDIT_STATUS, int cUSTOMER_ORDER_ID, int sALES_ORG, int cOMPANY_CODE,
			int sOLD_TO_PARTY, int cUSTOMER_NUMBER, double rELEASED_CREDIT_VALUE, double oRDER_AMOUNT,
			double aMOUNT_IN_USD, long uNIQUE_CUST_ID, int iD) {
		
		DISTRIBUTION_CHANNEL = dISTRIBUTION_CHANNEL;
		DIVISION = dIVISION;
		PURCHASE_ORDER_TYPE = pURCHASE_ORDER_TYPE;
		ORDER_CREATION_DATE = oRDER_CREATION_DATE;
		ORDER_CREATION_TIME = oRDER_CREATION_TIME;
		CREDIT_CONTROL_AREA = cREDIT_CONTROL_AREA;
		REQUESTED_DELIVERY_DATE = rEQUESTED_DELIVERY_DATE;
		ORDER_CURRENCY = oRDER_CURRENCY;
		CREDIT_STATUS = cREDIT_STATUS;
		CUSTOMER_ORDER_ID = cUSTOMER_ORDER_ID;
		SALES_ORG = sALES_ORG;
		COMPANY_CODE = cOMPANY_CODE;
		SOLD_TO_PARTY = sOLD_TO_PARTY;
		CUSTOMER_NUMBER = cUSTOMER_NUMBER;
		RELEASED_CREDIT_VALUE = rELEASED_CREDIT_VALUE;
		ORDER_AMOUNT = oRDER_AMOUNT;
		AMOUNT_IN_USD = aMOUNT_IN_USD;
		UNIQUE_CUST_ID = uNIQUE_CUST_ID;
		ID = iD;
	}

	public int getID() {
		return ID;
	}

	public void setID(int iD) {
		ID = iD;
	}

	public String getDISTRIBUTION_CHANNEL() {
		return DISTRIBUTION_CHANNEL;
	}

	public void setDISTRIBUTION_CHANNEL(String dISTRIBUTION_CHANNEL) {
		DISTRIBUTION_CHANNEL = dISTRIBUTION_CHANNEL;
	}

	public String getDIVISION() {
		return DIVISION;
	}

	public void setDIVISION(String dIVISION) {
		DIVISION = dIVISION;
	}

	public String getPURCHASE_ORDER_TYPE() {
		return PURCHASE_ORDER_TYPE;
	}

	public void setPURCHASE_ORDER_TYPE(String pURCHASE_ORDER_TYPE) {
		PURCHASE_ORDER_TYPE = pURCHASE_ORDER_TYPE;
	}

	public String getORDER_CREATION_DATE() {
		return ORDER_CREATION_DATE;
	}

	public void setORDER_CREATION_DATE(String oRDER_CREATION_DATE) {
		ORDER_CREATION_DATE = oRDER_CREATION_DATE;
	}

	public String getORDER_CREATION_TIME() {
		return ORDER_CREATION_TIME;
	}

	public void setORDER_CREATION_TIME(String oRDER_CREATION_TIME) {
		ORDER_CREATION_TIME = oRDER_CREATION_TIME;
	}

	public String getCREDIT_CONTROL_AREA() {
		return CREDIT_CONTROL_AREA;
	}

	public void setCREDIT_CONTROL_AREA(String cREDIT_CONTROL_AREA) {
		CREDIT_CONTROL_AREA = cREDIT_CONTROL_AREA;
	}

	public String getREQUESTED_DELIVERY_DATE() {
		return REQUESTED_DELIVERY_DATE;
	}

	public void setREQUESTED_DELIVERY_DATE(String rEQUESTED_DELIVERY_DATE) {
		REQUESTED_DELIVERY_DATE = rEQUESTED_DELIVERY_DATE;
	}

	public String getORDER_CURRENCY() {
		return ORDER_CURRENCY;
	}

	public void setORDER_CURRENCY(String oRDER_CURRENCY) {
		ORDER_CURRENCY = oRDER_CURRENCY;
	}

	public String getCREDIT_STATUS() {
		return CREDIT_STATUS;
	}

	public void setCREDIT_STATUS(String cREDIT_STATUS) {
		CREDIT_STATUS = cREDIT_STATUS;
	}

	public int getCUSTOMER_ORDER_ID() {
		return CUSTOMER_ORDER_ID;
	}

	public void setCUSTOMER_ORDER_ID(int cUSTOMER_ORDER_ID) {
		CUSTOMER_ORDER_ID = cUSTOMER_ORDER_ID;
	}

	public int getSALES_ORG() {
		return SALES_ORG;
	}

	public void setSALES_ORG(int sALES_ORG) {
		SALES_ORG = sALES_ORG;
	}

	public int getCOMPANY_CODE() {
		return COMPANY_CODE;
	}

	public void setCOMPANY_CODE(int cOMPANY_CODE) {
		COMPANY_CODE = cOMPANY_CODE;
	}

	public int getSOLD_TO_PARTY() {
		return SOLD_TO_PARTY;
	}

	public void setSOLD_TO_PARTY(int sOLD_TO_PARTY) {
		SOLD_TO_PARTY = sOLD_TO_PARTY;
	}

	public int getCUSTOMER_NUMBER() {
		return CUSTOMER_NUMBER;
	}

	public void setCUSTOMER_NUMBER(int cUSTOMER_NUMBER) {
		CUSTOMER_NUMBER = cUSTOMER_NUMBER;
	}

	public double getRELEASED_CREDIT_VALUE() {
		return RELEASED_CREDIT_VALUE;
	}

	public void setRELEASED_CREDIT_VALUE(double rELEASED_CREDIT_VALUE) {
		RELEASED_CREDIT_VALUE = rELEASED_CREDIT_VALUE;
	}

	public double getORDER_AMOUNT() {
		return ORDER_AMOUNT;
	}

	public void setORDER_AMOUNT(double oRDER_AMOUNT) {
		ORDER_AMOUNT = oRDER_AMOUNT;
	}

	public double getAMOUNT_IN_USD() {
		return AMOUNT_IN_USD;
	}

	public void setAMOUNT_IN_USD(double aMOUNT_IN_USD) {
		AMOUNT_IN_USD = aMOUNT_IN_USD;
	}

	public long getUNIQUE_CUST_ID() {
		return UNIQUE_CUST_ID;
	}

	public void setUNIQUE_CUST_ID(long uNIQUE_CUST_ID) {
		UNIQUE_CUST_ID = uNIQUE_CUST_ID;
	}

}
